NAME=jenkins-job-cli
VERSION=$(shell cat VERSION)
BUILD=$(shell git rev-parse --short HEAD)
EXT_LD_FLAGS="-Wl,--allow-multiple-definition"
LD_FLAGS="-s -w -X main.version=$(VERSION) -X main.build=$(BUILD) -extldflags=$(EXT_LD_FLAGS)"
TAP_REPO=jeffzhangc/homebrew-tap
RELEASE_REPO=jeffzhangc/jenkins-job-cli

# Default target
all: build

# Clean build artifacts
clean:
	rm -rf _build/ release/ dist/

# Build for current platform
build:
	go mod tidy
	CGO_ENABLED=0 go build -tags release -ldflags $(LD_FLAGS) -o $(NAME)

# Development build
build-dev:
	go build -ldflags "-w -X main.version=$(VERSION)-dev -X main.build=$(BUILD) -extldflags=$(EXT_LD_FLAGS)"

# Build for all platforms (legacy, kept for compatibility)
build-all: clean
	@echo "Building for all platforms..."
	mkdir -p _build
	GOOS=darwin  GOARCH=arm64 go build -tags release -ldflags $(LD_FLAGS) -o _build/$(NAME)-$(VERSION)-darwin-arm64
	GOOS=darwin  GOARCH=amd64 go build -tags release -ldflags $(LD_FLAGS) -o _build/$(NAME)-$(VERSION)-darwin-amd64
	GOOS=linux   GOARCH=amd64 go build -tags release -ldflags $(LD_FLAGS) -o _build/$(NAME)-$(VERSION)-linux-amd64
	GOOS=linux   GOARCH=arm   go build -tags release -ldflags $(LD_FLAGS) -o _build/$(NAME)-$(VERSION)-linux-arm
	GOOS=linux   GOARCH=arm64 go build -tags release -ldflags $(LD_FLAGS) -o _build/$(NAME)-$(VERSION)-linux-arm64
	GOOS=windows GOARCH=amd64 go build -tags release -ldflags $(LD_FLAGS) -o _build/$(NAME)-$(VERSION)-windows-amd64
	cd _build; shasum -a 256 * > sha256sums.txt
	@echo "Build completed."

# Docker image
image:
	docker build -t $(NAME) -f Dockerfile .

# Install to local system
install: build
	@echo "Installing $(NAME) to /usr/local/bin/..."
	sudo cp $(NAME) /usr/local/bin/jj
	@echo "Installation completed."

# Test GoReleaser configuration
goreleaser-check:
	@command -v goreleaser >/dev/null 2>&1 || { \
		echo "Error: goreleaser is required but not installed."; \
		echo "Install it from: https://goreleaser.com/install/"; \
		echo "Or run: brew install goreleaser"; \
		exit 1; \
	}
	goreleaser check

# Test build with GoReleaser (no release)
goreleaser-snapshot: clean goreleaser-check
	goreleaser release --snapshot 

# Full release with GoReleaser (includes Homebrew tap)
release: clean goreleaser-check
	@echo "Releasing version $(VERSION) with GoReleaser..."
	@if [ -z "$$GITHUB_TOKEN" ]; then \
		echo "Error: GITHUB_TOKEN is not set."; \
		echo "Please set it: export GITHUB_TOKEN=ghp_xxx"; \
		echo "Or run: gh auth login"; \
		exit 1; \
	fi
	goreleaser release

# Update Homebrew tap formula (standalone)
update-tap:
	@command -v gh >/dev/null 2>&1 || { \
		echo "Error: GitHub CLI (gh) is required but not installed."; \
		echo "Install it from: https://cli.github.com/"; \
		echo "Or run: brew install gh"; \
		exit 1; \
	}
	@echo "Updating Homebrew tap formula..."
	@if [ -z "$$GITHUB_TOKEN" ]; then \
		export GITHUB_TOKEN=$$(gh auth token); \
	fi
	# Clone tap repository
	rm -rf _tap_repo
	gh repo clone $(TAP_REPO) _tap_repo
	
	# Create or update formula
	cat > _tap_repo/Formula/$(NAME).rb << EOF
# This file is generated by GoReleaser. DO NOT EDIT.
class JenkinsJobCli < Formula
  desc "Jenkins Job CLI tool"
  homepage "https://github.com/$(RELEASE_REPO)"
  url "https://github.com/$(RELEASE_REPO)/releases/download/v$(VERSION)/$(NAME)_$(VERSION)_darwin_all.tar.gz"
  sha256 "$$(curl -sL https://github.com/$(RELEASE_REPO)/releases/download/v$(VERSION)/$(NAME)_$(VERSION)_darwin_all.tar.gz | shasum -a 256 | cut -d' ' -f1)"
  version "$(VERSION)"
  
  if Hardware::CPU.intel?
    url "https://github.com/$(RELEASE_REPO)/releases/download/v$(VERSION)/$(NAME)_$(VERSION)_darwin_amd64.tar.gz"
    sha256 "$$(curl -sL https://github.com/$(RELEASE_REPO)/releases/download/v$(VERSION)/$(NAME)_$(VERSION)_darwin_amd64.tar.gz | shasum -a 256 | cut -d' ' -f1)"
  end
  
  if Hardware::CPU.arm?
    url "https://github.com/$(RELEASE_REPO)/releases/download/v$(VERSION)/$(NAME)_$(VERSION)_darwin_arm64.tar.gz"
    sha256 "$$(curl -sL https://github.com/$(RELEASE_REPO)/releases/download/v$(VERSION)/$(NAME)_$(VERSION)_darwin_arm64.tar.gz | shasum -a 256 | cut -d' ' -f1)"
  end

  def install
    bin.install "$(NAME)"
    bin.install_symlink bin/$(NAME) => "jj"
  end

  test do
    system "\#{bin}/$(NAME) --version"
  end
end
EOF
	
	# Commit and push changes
	cd _tap_repo && \
	git add Formula/$(NAME).rb && \
	git commit -m "Update $(NAME) to v$(VERSION)" && \
	git push origin main
	
	# Cleanup
	rm -rf _tap_repo
	@echo "Homebrew tap updated successfully!"

# Initialize GoReleaser configuration
goreleaser-init:
	@command -v goreleaser >/dev/null 2>&1 || { \
		echo "Error: goreleaser is required but not installed."; \
		echo "Install it from: https://goreleaser.com/install/"; \
		exit 1; \
	}
	goreleaser init

# Full release pipeline (release + update tap)
full-release: release update-tap
	@echo "Full release with Homebrew tap completed!"

# Show help
help:
	@echo "Available targets:"
	@echo "  build              - Build for current platform"
	@echo "  build-dev          - Development build"
	@echo "  build-all          - Build for all platforms (legacy)"
	@echo "  release            - Release with GoReleaser (main target)"
	@echo "  goreleaser-snapshot- Test build with GoReleaser"
	@echo "  goreleaser-check   - Check GoReleaser configuration"
	@echo "  update-tap         - Update Homebrew tap formula only"
	@echo "  full-release       - Release + update Homebrew tap"
	@echo "  install            - Install to /usr/local/bin/"
	@echo "  clean              - Clean build artifacts"

.PHONY: all clean build build-dev build-all image install goreleaser-check goreleaser-snapshot release update-tap goreleaser-init full-release help